name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 9 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "0xb5115a66f7fa4d13e5bdf6eabe84137dfa9e402c@skiff.com"
          git config --local user.name "KajiuraLove"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
